name: flutter_package_manager
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  gradient_app_bar: ^0.1.3
  calendarro: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/4x/gift@4x.png"
  adaptive_icon_background: "#ffffff"

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/images/
  - assets/images/1x/
  - assets/images/1.5x/
  - assets/images/2x/
  - assets/images/3x/
  - assets/images/4x/
  - assets/images/CustomX/
  - assets/images/CustomX/Gift-500x.png

  fonts:
    - family: rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/Rubik/Rubik-Black.ttf
          weight: 900

